### ISSUE TITLE
Please add a license file and a screen shot

### ISSUE THREAD

**Issue by unixorn** [idaMakelaWork/ohmyzshtheme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I only add themes with screen shots in the readme so that users can see what they look like without having to install them.

Also, please add a license file, some people won't use any code that doesn't have an open source license. If you don't have one in mind, https://choosealicense.com is a good resource to help you select an appropriate one.

ohmyzshtheme is very generic. Please consider renaming the repository to something more descriptive, or even just name it `refined-custom` after the plugin file.

Finally, don't take these as criticisms of the work you've done, they're meant to make a more useful entry in the plugin/theme list.

Thanks!

**Comment by idaMakelaWork** [comment]
Hello!

Thank you so much for reaching out! I'll see what I can do!
I mainly uploaded it so I could share it from my work to my personal GitHub and didn't think anyone would take an interest. So cool though! 

I'll update the issue when I've made changes 🤗

**Comment by idaMakelaWork** [comment]
The repository is now updated with a readme, including a screenshot, and a license. 🙌
